version: '3'
services:

  fleet-api:
    volumes:
      - ./nodejs:/usr/src/app
      - /usr/src/app/node_modules
    command:
      npx nest start --watch

  mongo:
    ports:
      - "27017:27017"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
