version: '3'
services:

  fleet-api:
    build:
      context: ./nodejs
      dockerfile: Dockerfile-app
      args:
        app: fleet-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq

  drive-simulation-service:
    build:
      context: ./nodejs
      dockerfile: Dockerfile-app
      args:
        app: drive-simulation-service
    env_file: .env
    depends_on:
      - mongo
      - rabbitmq

  drive-penalty-service:
    build:
      context: ./nodejs
      dockerfile: Dockerfile-app
      args:
        app: drive-penalty-service
    env_file: .env
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: "mongo:latest"
    expose:
      - 27017
    volumes:
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/mongo/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: fms

  rabbitmq:
    image: "rabbitmq:3-management"
    expose:
      - 5672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/