version: '3'
services:

  fleet-api:
    build: ./fleet-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    command:
      bash -c "node ./dist/main.js"

  drive-simulation-service:
    build: ./drive-simulation-service
    env_file: .env
    depends_on:
      - mongo
      - rabbitmq
    command:
      bash -c "node ./dist/main.js"

  drive-penalty-service:
    build: ./drive-penalty-service
    env_file: .env
    depends_on:
      - mongo
      - rabbitmq
    command:
      bash -c "node ./dist/main.js"

  mongo:
    image: "mongo:latest"
    expose:
      - 27017
    volumes:
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/mongo/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: fms

  rabbitmq:
    image: "rabbitmq:3-management"
    expose:
      - 5672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/