
### BUILD CONTAINER
FROM node:12 AS build
ARG app

WORKDIR /usr/src/app

COPY nest*.json ./
COPY package*.json ./
COPY tsconfig*.json ./
RUN CI=true npm ci

COPY libs libs
COPY apps/$app apps/$app
RUN npm run build $app


### RELEASE CONTAINER
FROM node:12 AS release
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist /usr/src/app/dist
COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY package.json package.json
COPY package-lock.json package-lock.json

CMD [ "node", "./dist/main.js" ]

